### ISSUE TITLE
Advent/day24.nt erro

### ISSUE THREAD

**Issue by wilsonk** [Neat-Lang/neat#35]
I am getting this error with the newest neat compiler as of Jan 6, 2024:

```
/neat/build/src/std/container/binheap.nt:22:
    this(this.heapier) { }
         ~~~~~~~~~~~~ Cannot assign quarantined type to occluded container field.
```

Not sure how to fix it. Neat is great, btw ;)  Some very interesting ideas/implementations in the language.

**Comment by FeepingCreature** [comment]
Woops, fixed. Closure handling was changed a lot last year; classes can no longer hold references to non-refcounted (stack allocated) closures, because they might be hidden from the refcounter and thus escape, leading to an invalid call. Luckily this is easily worked around by just heap allocating the lambda.
